### ISSUE TITLE
Feature request: Place "default" files at the top of list

### ISSUE THREAD

**Issue by SeanBannister** [jsdelivr/plugin-vs-code#2]
When you go to jsDelivr.com and search for a package ([for example lodash](https://www.jsdelivr.com/package/npm/lodash)) it shows the "default" file at the top so the user can easily find the most common file:
![image](https://user-images.githubusercontent.com/197231/82136581-b8990e00-9852-11ea-8e07-e243d2b17e3d.png)

However when we search for lodash with this extension in VS Code the default isn't specified at the top of the list which makes it extremely hard to find on projects with a lot of files, for example:
![image](https://user-images.githubusercontent.com/197231/82136607-f9912280-9852-11ea-85d8-bc48270af721.png)

**Comment by MartinKolarik** [comment]
👍 would you like to send a PR for this? The relevant file is [here](https://github.com/jsdelivr/plugin-vs-code/blob/master/src/steps/pickFile.js) and the correct default file can be read from `response.body`.
