### ISSUE TITLE
Unexpected error occurred

### ISSUE THREAD

**Issue by brainz80** [jsdelivr/plugin-vs-code#5]
I keep getting `Unexpected error occurred` when trying to install e.g. `minify-css-string`

**Comment by brainz80** [comment]
Decided to dig around the source abit, and went built this locally. The problem seems to be a expired certificate.

**Comment by brainz80** [comment]
Made a pull-request #6

**Comment by MartinKolarik** [comment]
Thanks for checking. An invalid certificate is not something to ignore. What certificate are you getting, exactly?

**Comment by brainz80** [comment]
Looks like it's the one delivered by `https://data.jsdelivr.com/`

Here's the error:

```ini
code:'CERT_HAS_EXPIRED'
gotOptions:{path: '/v1/package/npm/lodash@4.17.21/flat', protocol: 'https:', hostname: 'data.jsdelivr.com', hash: '', search: '', …}
host:undefined
hostname:'data.jsdelivr.com'
method:'GET'
name:'RequestError'
path:'/v1/package/npm/lodash@4.17.21/flat'
protocol:'https:'
socketPath:undefined
url:'https://data.jsdelivr.com/v1/package/npm/lodash@4.17.21/flat'
message:'certificate has expired'
stack:'RequestError: certificate has expired\n    at ClientRequest.<anonymous> (d:\\Programming\\node.js\\vsode-jsdelivr\\node_modules\\got\\source\\request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:327:22)\n    at ClientRequest.<anonymous> (d:\\Programming\\node.js\\vsode-jsdelivr\\node_modules\\@szmarczak\\http-timer\\source\\index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)'
```

This is what I get when querying the endpoint on Chrome:

![image](https://user-images.githubusercontent.com/1257591/146046845-aed56d22-ba86-43f4-bf89-4a7ca9a1c36d.png)

I'm stumped. According to Chrome the credential should have been updated 12.12.2021 - yet the above error tells it's expired.

**Comment by MartinKolarik** [comment]
This is usually an issue with an antivirus, or other security software on your machine, or possibly with clock configuration.

**Comment by brainz80** [comment]
I believe this issue is related to [https://github.com/microsoft/vscode/issues/102252](https://github.com/microsoft/vscode/issues/102252)
Which is related to [https://github.com/electron/electron/pull/25313](https://github.com/electron/electron/pull/25313)

**Comment by brainz80** [comment]
I ran command mentioned in [https://github.com/microsoft/vscode/issues/102252](https://github.com/microsoft/vscode/issues/102252)  `openssl s_client -showcerts -servername <server> -connect <server:443>`

Here's a snip of the cert-chain:
```
 0 s:CN = data.jsdelivr.com i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3 i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1 i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

```
SSL handshake has read 4580 bytes and written 389 bytes
Verification: OK
```

**Comment by jimaek** [comment]
Since this is unrelated to the addon itself I believe its safe to close this issue? :)

**Comment by nuxodin** [comment]
I also have this error
